Minimum h5py version is now 2.3
h5py 2.3 (released in April 2014) added support for arbitrary vlen data,
which is used to store binary telstate pickles in the latest v3.9 HDF5
files. Older versions of h5py elicit the following error:

  TypeError: No NumPy equivalent for TypeVlenID exists