Fix support on older NumPy
NumPy 1.12 lets np.full(shape, value) determine the dtype from the
supplied value. On older versions of NumPy the dtype of _time_keep
should be fixed to bool, otherwise things croak later on with the
message:

  TypeError: ufunc 'bitwise_and' not supported for the input types, and
  the inputs could not be safely coerced to any supported types
  according to the casting rule ''safe''

Since Ubuntu 16.04 aka Xenial (the current LTS release) still has
NumPy 1.11, this is something to fix.